@startuml gestion_magasin
left to right direction

actor Admin

rectangle gestion_magasin{
    usecase "consulter les produits" as UC1
    usecase "ajouter un produit dans le store" as UC2
    usecase "modifier un produit" as UC3
    usecase "supprimer produit" as UC4
    usecase "rechercher produit" as UC5
}

Admin -- UC1
Admin -- UC2
Admin -- UC3
Admin -- UC4
Admin -- UC5


usecase "authentification" as Auth

UC1 -- (Auth) : <<include>>
UC2 -- (Auth) : <<include>>
UC3 -- (Auth) : <<include>>
UC4 -- (Auth) : <<include>>
UC5 -- (Auth) : <<include>>